name: Monthly ChartInk Stock Scraper

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  schedule:
    # Runs at 00:00 on the 1st day of every month
    - cron: '0 0 1 * *'

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run the scraper script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
        run: python main.py