# .github/workflows/scheduled_scrape.yml
name: Monthly ChartInk Stock Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}

      - name: Install Playwright browsers if cache missed
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: playwright install --with-deps firefox

      - name: Run the scraper script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
        run: python -m app.main